services:
  postgres:
    image: postgres:17
    ports:
      - '5431:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Bhawesh@123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
